#!/bin/sh

pip install -U --no-deps git+git://github.com/Theano/Theano.git
conda install -y openblas

pip install git+https://github.com/Lasagne/Lasagne
pip install git+https://github.com/mehdidc/lasagnekit
pip install git+https://github.com/dnouri/nolearn.git@master#egg=nolearn==0.7.git
pip install git+https://github.com/fchollet/keras

# tensorflow

pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl

# Torch
rm "$HOME/miniconda2/lib/libreadline.so.6"
sudo apt-get install -y cmake libreadline-dev libzmq-dev
curl -s https://raw.githubusercontent.com/torch/ezinstall/master/install-deps | bash
git clone https://github.com/torch/distro.git ~/torch --recursive
cd ~/torch; ./install.sh
