#!/bin/sh

install_openblas() {
}

pip install -U --no-deps git+git://github.com/Theano/Theano.git
install_openblas # for theano
conda install -y -c https://conda.binstar.org/jakirkham openblas

# nolearn + lasagne + lasagnekit + keras
pip install git+https://github.com/Lasagne/Lasagne
pip install git+https://github.com/mehdidc/lasagnekit
pip install nolearn
pip install git+https://github.com/fchollet/keras

# tensorflow

pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl

# Torch
sudo apt-get install -y cmake libreadline-dev libzmq-dev
curl -s https://raw.githubusercontent.com/torch/ezinstall/master/install-deps | bash
git clone https://github.com/torch/distro.git ~/torch --recursive
cd ~/torch; ./install.sh

